name: solid
description: Solid allows use of Tim Berners-Lee's new platform for a decentralized web, https://solid.inrupt.com/, from within dart. Currently only includes solid.auth.
version: 0.2.2
homepage: https://github.com/TheJamesBM/solid-dart
author: James Madden <jamesbmadden@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
